'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("The_Trip_Wire.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Cheeze() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cheeze", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property closed_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closed!", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gun_hi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gun-hi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main_player() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main player", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main_player2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main player2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main_player3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main player3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player_with_weapon_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player with weapon 3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player_with_weapon_31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player with weapon 31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property player9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PlayerStand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlayerStand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PlayerStandLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlayerStandLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PlayerWalk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlayerWalk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PlayerWalk2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlayerWalk2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property playerwithweapon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("playerwithweapon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property playerwithweapon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("playerwithweapon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property playerwithweapon21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("playerwithweapon21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property russia_eagle2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("russia_eagle2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sticker_375x360() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sticker,375x360", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property The_Trip__Wire_picture() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("The Trip -Wire-picture", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Treasure_Chest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Treasure_Chest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Untitled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Untitled1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Untitled123() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled123", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Untitled2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property איש_מינרות() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("איש מינרות", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property בלוק_2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("בלוק!2!", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property גולגולת() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("גולגולת", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property לפיד() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("לפיד", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property לפיד1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("לפיד1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ענדה_מעחור() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ענדה מעחור", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property רקע() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("רקע", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property רקע1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("רקע1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
